version: '3.1'

networks:
  web-network:

services:
  apache:
    image: httpd:2.4
    build:
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
    networks:
      - web-network

  php-cli:
    image: php:8.2-cli
    tty: true # Make it survive longer than 0s
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
    networks:
      - web-network

  docker-php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      MYSQL_DB: "${DB_URL}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
    networks:
      - web-network

  docker-db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - ./docker/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - web-network
