version: '3.1'

networks:
  web-network:

services:
  docker-apache2:
    image: httpd:2.4
    build:
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
    networks:
      - web-network

  docker-php-fpm:
    image: php:8.2-fpm
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
    networks:
      - web-network

  # mysql:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
